# Generated by Django 4.2.5 on 2023-11-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_first_name_student_nname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="nname", new_name="name",
        ),
    ]
